name: CI
on:
  push:
    branches:
      - "*"

jobs:
  build:
    strategy:
      matrix:
        java: [14]

    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Setup Java ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      
      - name: Checkout Project
        uses: actions/checkout@v2

      - name: Checkout OpenSearch
        uses: actions/checkout@v2
        with:
          repository: 'opensearch-project/.github'
          path: .github
      
      - name: Build and Run Tests
        run: |
          ./.github/scripts/build.sh
      
      - name: Run Integ Tests
        run: |
          ./.github/scripts/integ-test.sh
      
      - name: Upload Code Coverage
        uses: codecov/codecov-action@v1
        with:
          file: ./build/reports/jacoco/test/jacocoTestReport.xml
          flags: plugin
      
      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_STAGING_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_STAGING_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      
      - name: Publish Snapshots
        run: |
          ./.github/scripts/publish-snapshot.sh