name: CI
on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  build:
    strategy:
      matrix:
        java: [14]

    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Setup Java ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
        
      - name: Checkout Project
        uses: actions/checkout@v2

      - name: Checkout opensearch-project/.github
        uses: actions/checkout@v2
        with:
          repository: 'opensearch-project/.github'
          path: opensearch-github
      
      - name: DCO Signoff Check
        run: |
          ./opensearch-github/scripts/signoff-check.sh 
          
      - name: Build and Run Tests
        run: |
          ./opensearch-github/scripts/build.sh
      
      - name: Upload Code Coverage
        uses: codecov/codecov-action@v1
        with:
          file: ./build/reports/jacoco/test/jacocoTestReport.xml
          flags: plugin
