name: Release
on: workflow_dispatch

jobs:
  build:
    strategy:
      matrix:
        java: [14]

    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Setup Java ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_STAGING_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_STAGING_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      
      - name: Checkout Project
        uses: actions/checkout@v2

      - name: Checkout OpenSearch
        uses: actions/checkout@v2
        with:
          repository: 'opensearch-project/.github'
          path: .github
      
      - name: Stage Artifacts for Release
        run: |
          ./.github/scripts/publish-staging.sh